### PR TITLE
GRASS7: Update to 7.8.6RC2

### PR DESCRIPTION
**Pull request by ninsbl**

### CODE REVIEW

**Comment by jef-n** [comment]
"Already" started building 7.8.6RC2 - a little bit before this PR.  There's no tarball on download.osgeo.org - so that needed to be changed too - and downloading the one from grass.osgeo.org took ages (including a number of reconnects)…

**Comment by ninsbl** [comment]
Ok. Nice! What about downloading the tarball from github?

https://github.com/OSGeo/grass/archive/refs/tags/7.8.6RC2.tar.gz

**Comment by jef-n** [comment]
> https://github.com/OSGeo/grass/archive/refs/tags/7.8.6RC2.tar.gz

<8s

**Comment by jef-n** [comment]
superceeded by 5086696de7e0417f7b69b6bb18205923dd1c2451

**Pull request closed without merging**
